---
- name: Create multiple VM
  hosts: localhost
#  name: Choose oVirt engine
#  gather_facts: false
#  vars_prompt:
#    - name: engine
#      prompt: "Please, choose engine"
#      private: no
#      vars:
#        hostname: "{{ engine }}"
#        url: "{{ host }}"
#      vars_files:
#      - engine.yml
  tasks:
    - name: Login in engine with using user/password
      ovirt_auth:
         url: "https://engine0902.dc.rk/ovirt-engine/api"
         username: admin@internal
         password: '!h:24bu<]7%O$0a^'
         insecure: yes

    - name: Parse 1vms.csv input file
      read_csv:
           path: 1vms.csv
           key: name
      register: vms

    - name: Creates a new Virtual Machine from template
      ovirt_vm:
           auth: "{{ ovirt_auth }}"
           state: present
           name: "{{ item.value.name }}"
           template: Centos-cloud-unprovisioned
           storage_domain: cephfs_hdd
           cluster: "{{ item.value.cluster }}"
           memory: "{{ item.value.memory }}GiB"
           memory_guaranteed: "{{ item.value.memory_guaranteed }}GiB"
           cpu_cores: "{{ item.value.cpu_cores }}"
           cpu_sockets: "{{ item.value.cpu_sockets }}"
           type: "{{ item.value.class }}"
      loop: "{{ vms.dict|dict2items }}"

    - name: upsize vm's disk.
      ovirt_disk:
         auth: "{{ ovirt_auth }}"
         name: Centos7-Cloud
         vm_name: "{{ item.value.name }}"
         size: 128GiB
         interface: virtio
         state: present
      loop: "{{ vms.dict|dict2items }}"


    - name: Cloud_init running
      ovirt_vm:
        wait: no
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ item.value.name }}"
        cloud_init:
           dns_servers: "{{ item.value.dns1 }} {{ item.value.dns2 }}"
           nic_ip_address: "{{ item.value.ip }}"
           nic_netmask: "{{ item.value.mask }}"
           nic_gateway: "{{ item.value.gw }}"
           nic_name: "{{ item.value.nic }}"
           nic_boot_protocol: static
           nic_on_boot: true
           host_name: "{{ item.value.fqdn }}"
           user_name: root
           root_password: "12332145"
      loop: "{{ vms.dict|dict2items }}"